<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="User-PC" ignored="0" name="Default test" tests="2" failures="2" timestamp="23 Feb 2020 16:33:51 GMT" time="55.52" errors="0">
  <testcase name="runScenario" time="40.081" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [x1] but found [Module Quiz]">
      <![CDATA[java.lang.AssertionError: expected [x1] but found [Module Quiz]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at stepdef.ToolsStepDefinition.user_validates_link_with(ToolsStepDefinition.java:42)
at ✽.user validates link with ""(file:src/test/resources/features/feat1.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="15.191" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [x1] but found [Module Quiz]">
      <![CDATA[java.lang.AssertionError: expected [x1] but found [Module Quiz]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at stepdef.ToolsStepDefinition.user_validates_link_with(ToolsStepDefinition.java:42)
at ✽.user validates link with ""(file:src/test/resources/features/feat2.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
