<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="User-PC" name="runner.RunnerIT" tests="2" failures="2" timestamp="23 Feb 2020 14:16:44 GMT" time="128.103" errors="0">
  <testcase name="runScenario" time="78.483" classname="runner.RunnerIT">
    <failure type="java.lang.AssertionError" message="expected [x1] but found [Module Quiz]">
      <![CDATA[java.lang.AssertionError: expected [x1] but found [Module Quiz]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at stepdef.ToolsStepDefinition.user_validates_link_with(ToolsStepDefinition.java:42)
at ✽.user validates link with ""(file:src/test/resources/features/feat1.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="49.620" classname="runner.RunnerIT">
    <failure type="java.lang.AssertionError" message="expected [x1] but found [Module Quiz]">
      <![CDATA[java.lang.AssertionError: expected [x1] but found [Module Quiz]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at stepdef.ToolsStepDefinition.user_validates_link_with(ToolsStepDefinition.java:42)
at ✽.user validates link with ""(file:src/test/resources/features/feat2.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.RunnerIT -->
